# Generated by Django 3.1.5 on 2021-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0004_auto_20210310_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='target_tag',
            field=models.TextField(blank=True),
        ),
    ]
